spring:
  datasource:
    url: jdbc:h2:file:c:/temp/rcp_h2;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

server:
  port: 8081
